version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev

jobs:
  test-site:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn && bundle install --path vendor/bundle
      - run:
          name: Build the site resources
          command: yarn run build
      - run:
          name: Run the site server
          command: bundle exec jekyll serve -P 80 -H 0.0.0.0
          background: true
      - run:
          name: Check site is accessible
          command: sleep 1 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost
  lint-nginx:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install gixy
          command: pip3 install gixy
      - run:
          name: Lint nginx configuration files
          command: gixy nginx.conf
  lint-scss:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint sass
          command: yarn lint-scss

workflows:
  version: 2
  build:
    jobs:
      - test-site
      - lint-nginx
      - lint-scss
